services:
  web:
    build: .
    ports:
      - "8090:5000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/data/warehouse.db
      - SECRET_KEY=miniwms-secret-key-change-in-production